name: DeployStaging

on:
  pull_request:
    branches:
      - staging
  push:
    branches:
      - staging

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2

    - name: AWS CDK GitHub Actions - Diff
      if: github.event_name == 'pull_request'
      id: diff
      uses: youyo/aws-cdk-github-actions@v1.1.10
      with:
        cdk_subcommand: 'diff'
        cdk_stack: 'nlp-ecs-cluster-stg'
        actions_comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.CUSTOM_GIT_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-west-2'

    - name: AWS CDK - Deploy to Staging
      if: github.event_name == 'push'
      uses: youyo/aws-cdk-github-actions@v1.1.10
      with:
        cdk_subcommand: 'deploy'
        cdk_stack: 'nlp-ecs-cluster-stg'
        actions_comment: false
        args: '--require-approval never'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-west-2'

    - name: Slack Notification
      if: github.event_name == 'push'
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_CHANNEL: nlp-billing-test
        SLACK_COLOR: '#3278BD'
        SLACK_TITLE: Cluster updated
        SLACK_MESSAGE: 'Post Content :rocket:'
        SLACK_USERNAME: ${{ github.event.repository.name }}-bot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_NLP_ALERTS }}

    - name: Open Issue
      if: failure() && github.event_name == 'pull_request'
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/issues \
        --header 'authorization: Bearer ${{ secrets.CUSTOM_GIT_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "title": "Automated issue for commit: ${{ github.sha }}",
          "body": "This issue was automatically created by GitHub Actions workflow **${{ github.workflow}}**. \n\n The commit hash was: _${{ github.sha }}_.",
          "assignees": ["${{ github.event.pull_request.user.login }}"]
          }'
